In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [2]:
df=pd.read_csv("Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
df=df.drop(['RowNumber',	'CustomerId',	'Surname'],axis=1)

In [4]:
label_encoder_gender=LabelEncoder()
df['Gender']=label_encoder_gender.fit_transform(df['Gender'])

In [5]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder(sparse_output=False)
geo_encoder=onehot_encoder_geo.fit_transform(df[['Geography']])
geo_encoded_df=pd.DataFrame(geo_encoder,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [6]:
df=pd.concat([df.drop('Geography',axis=1),geo_encoded_df],axis=1)
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [7]:
X=df.drop('EstimatedSalary',axis=1)
y=df['EstimatedSalary']

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
print(X_train.columns)

Index(['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts',
       'HasCrCard', 'IsActiveMember', 'Exited', 'Geography_France',
       'Geography_Germany', 'Geography_Spain'],
      dtype='object')

In [10]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
with open ('label_encoder_gender.pkl','wb') as file:
  pickle.dump(label_encoder_gender,file)
  
with open ('onehot_encoder_geo.pkl','wb') as file:
  pickle.dump(onehot_encoder_geo,file)
  
with open('scaler.pkl','wb') as file:
  pickle.dump(scaler,file)

## ANN Regression Problem statement

In [13]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [14]:
model=Sequential([
  Dense(64,activation='relu',input_shape=(X_train.shape[1],)),## HL1
  Dense(32,activation='relu'),##HL2
  Dense(1)## output layer for regression
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

c:\Users\ANGAN -AGNIBHO\ANN Classification\venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

# set up tensorboard
log_dir="regression/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [17]:
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [18]:
history=model.fit(
  X_train,y_train,validation_data=(X_test,y_test),epochs=100,
  callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 100364.8281 - mae: 100364.8281 - val_loss: 98478.4609 - val_mae: 98478.4609
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 99541.9062 - mae: 99541.9062 - val_loss: 96848.4609 - val_mae: 96848.4609
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 96742.8438 - mae: 96742.8438 - val_loss: 92756.4609 - val_mae: 92756.4609
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 91330.2656 - mae: 91330.2656 - val_loss: 86045.3828 - val_mae: 86045.3828
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 83519.8672 - mae: 83519.8672 - val_loss: 77456.4609 - val_mae: 77456.4609
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 74415.8516 - mae: 74415.8516 - val_loss: 68630.5312 - val_mae: 68630.5312
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 65688.7344 - mae: 65688.7344 - val_loss: 61129.0273 - val_mae: 61129.0273
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 58802.4023 - mae: 58802.4023 - val_loss: 55834.2461 - val_mae: 55834.2461
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 54469.4688 - mae: 54469.4688 - val_loss: 52884.1992 - val_mae: 52884.1992
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 52141.8438 - mae: 52141.8438 - val_loss: 51550.9609 - val_mae: 51550.9609
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 51099.9102 - mae: 51099.9102 - val_loss: 51090.8672 - val_mae: 51090.8672
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50687.3750 - mae: 50687.3750 - val_loss: 50900.1172 - val_mae: 50900.1172
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50500.2578 - mae: 50500.2578 - val_loss: 50816.2227 - val_mae: 50816.2227
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50395.0547 - mae: 50395.0547 - val_loss: 50751.3906 - val_mae: 50751.3906
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50313.8008 - mae: 50313.8008 - val_loss: 50701.8945 - val_mae: 50701.8945
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50255.8242 - mae: 50255.8242 - val_loss: 50654.6367 - val_mae: 50654.6367
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50193.5430 - mae: 50193.5430 - val_loss: 50605.1172 - val_mae: 50605.1172
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50146.9531 - mae: 50146.9531 - val_loss: 50572.1758 - val_mae: 50572.1758
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50101.2227 - mae: 50101.2227 - val_loss: 50529.4258 - val_mae: 50529.4258
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50058.4883 - mae: 50058.4883 - val_loss: 50497.4805 - val_mae: 50497.4805
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50020.2148 - mae: 50020.2148 - val_loss: 50473.2188 - val_mae: 50473.2188
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49986.3672 - mae: 49986.3672 - val_loss: 50443.8398 - val_mae: 50443.8398
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49955.9648 - mae: 49955.9648 - val_loss: 50425.4414 - val_mae: 50425.4414
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49928.6562 - mae: 49928.6562 - val_loss: 50402.5273 - val_mae: 50402.5273
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49904.5586 - mae: 49904.5586 - val_loss: 50389.1328 - val_mae: 50389.1328
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49880.5039 - mae: 49880.5039 - val_loss: 50372.1406 - val_mae: 50372.1406
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49852.9883 - mae: 49852.9883 - val_loss: 50359.2578 - val_mae: 50359.2578
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49837.0703 - mae: 49837.0703 - val_loss: 50352.4062 - val_mae: 50352.4062
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49813.8125 - mae: 49813.8125 - val_loss: 50335.8086 - val_mae: 50335.8086
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49797.6914 - mae: 49797.6914 - val_loss: 50335.4570 - val_mae: 50335.4570
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49779.6641 - mae: 49779.6641 - val_loss: 50318.3281 - val_mae: 50318.3281
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49759.6445 - mae: 49759.6445 - val_loss: 50310.3164 - val_mae: 50310.3164
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49743.4688 - mae: 49743.4688 - val_loss: 50303.3555 - val_mae: 50303.3555
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49726.7852 - mae: 49726.7852 - val_loss: 50301.7891 - val_mae: 50301.7891
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49710.7734 - mae: 49710.7734 - val_loss: 50295.2266 - val_mae: 50295.2266
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49696.1484 - mae: 49696.1484 - val_loss: 50288.8867 - val_mae: 50288.8867
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49684.0156 - mae: 49684.0156 - val_loss: 50282.6602 - val_mae: 50282.6602
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49670.5938 - mae: 49670.5938 - val_loss: 50272.2891 - val_mae: 50272.2891
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49661.5742 - mae: 49661.5742 - val_loss: 50265.8203 - val_mae: 50265.8203
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49645.9375 - mae: 49645.9375 - val_loss: 50275.3945 - val_mae: 50275.3945
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49633.5547 - mae: 49633.5547 - val_loss: 50277.6367 - val_mae: 50277.6367
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49626.8984 - mae: 49626.8984 - val_loss: 50281.4023 - val_mae: 50281.4023
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49617.2344 - mae: 49617.2344 - val_loss: 50280.7969 - val_mae: 50280.7969
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49607.8008 - mae: 49607.8008 - val_loss: 50269.9609 - val_mae: 50269.9609
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49598.0273 - mae: 49598.0273 - val_loss: 50265.3750 - val_mae: 50265.3750
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49588.5117 - mae: 49588.5117 - val_loss: 50265.5469 - val_mae: 50265.5469
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49575.6562 - mae: 49575.6562 - val_loss: 50267.4297 - val_mae: 50267.4297
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49570.4023 - mae: 49570.4023 - val_loss: 50268.0625 - val_mae: 50268.0625
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49563.9805 - mae: 49563.9805 - val_loss: 50262.4961 - val_mae: 50262.4961
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49557.0938 - mae: 49557.0938 - val_loss: 50271.2305 - val_mae: 50271.2305
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49545.1172 - mae: 49545.1172 - val_loss: 50272.1367 - val_mae: 50272.1367
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49538.3438 - mae: 49538.3438 - val_loss: 50270.0391 - val_mae: 50270.0391
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49532.4453 - mae: 49532.4453 - val_loss: 50264.7695 - val_mae: 50264.7695
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49528.5938 - mae: 49528.5938 - val_loss: 50288.1211 - val_mae: 50288.1211
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49518.0117 - mae: 49518.0117 - val_loss: 50283.4531 - val_mae: 50283.4531
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49512.5859 - mae: 49512.5859 - val_loss: 50282.2578 - val_mae: 50282.2578
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49505.9023 - mae: 49505.9023 - val_loss: 50270.6875 - val_mae: 50270.6875
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49495.7812 - mae: 49495.7812 - val_loss: 50274.6328 - val_mae: 50274.6328
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49489.8750 - mae: 49489.8750 - val_loss: 50270.1289 - val_mae: 50270.1289

In [19]:
## load Tensorboard Extension
%load_ext tensorboard

In [20]:
%tensorboard --logdir regression/fit

Reusing TensorBoard on port 6007 (pid 14256), started 2 days, 21:14:57 ago. (Use '!kill 14256' to kill it.)

In [24]:
## evaluate the model on the test data
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 50347.2344 - mae: 50347.2344
Test MAE : 50347.234375

In [25]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.